### ISSUE TITLE
UML class diagram

### ISSUE THREAD

**Issue by mswanson-mscst** [southeastmn-edu-2754/movie-corner#2]
After the team has completed the consolidated class worksheet/user stories document, each team member should individually create a conceptual class diagram using Visual Paradigm. Post a screenshot of your class diagram here.

**Comment by justin-sultze-mscs** [comment]
Here's my conceptual class diagram

![Justin Sultze Movie Corner ERD](https://user-images.githubusercontent.com/37412631/73736939-48cda000-4707-11ea-8ec8-f449717955c5.JPG)

**Comment by jseppa-mscs** [comment]
![ERDscreenshot](https://user-images.githubusercontent.com/42839541/73759570-c27a8380-4731-11ea-99e2-1360a3278455.JPG)

**Comment by jseppa-mscs** [comment]
![ERDscreenshot](https://user-images.githubusercontent.com/42839541/73759805-171dfe80-4732-11ea-9848-c98456cac163.JPG)

**Comment by ummer-siddique-mscs** [comment]
![image](https://user-images.githubusercontent.com/31634544/73811237-93e6c200-479e-11ea-93dd-a5b4cca7fa4d.png)

**Comment by mswanson-mscst** [comment]
I'm working on getting the movie/actors data that we'll need for the application, and found that the IMDb webapi has very limited search features. They have a lot of data available for download, though, so I made a recording that shows the procedure I used for downloading the text files from IMDb and importing the data into SQL Server:

2754 2020 031 IMDb download, import
https://mediaspace.minnstate.edu/media/2754+2020+031+IMDb+download%2C+import.mp4/1_rnipfb6u

Hopefully, by tomorrow I'll have a cleaned up version of the database that you can work with in getting started on the project.

**Comment by mswanson-mscst** [comment]
I'm working on getting the movie/actors data that we'll need for the application, and found that the IMDb webapi has very limited search features. They have a lot of data available for download, though, so I made a recording that shows the procedure I used for downloading the text files from IMDb and importing the data into SQL Server:

2754 2020 031 IMDb download, import
[https://mediaspace.minnstate.edu/media/2754+2020+031+IMDb+download%2C+import.mp4/1_rnipfb6u](url)

Hopefully, by tomorrow I'll have a cleaned up version of the database that you can work with in getting started on the project.

**Comment by mswanson-mscst** [comment]
I'm putting the finishing touches on the IMDb database that I imported. The movie genre information wasn't normalized, and it's taking a long time to create the m:n table between movies and genres. For a preview, here's the current structure:

![2754MovieDbDiagram01](https://user-images.githubusercontent.com/10352002/74076453-b4e92600-49dd-11ea-8db6-c1c7b8040128.png)

The two most important tables are:
- title_basics: contains basic information about each movie
- name_basics: contains names of all artists (actors, directors, etc.)

I'll post the database files in D2L tomorrow morning so you can download them to your machine. The sample data includes roughly:

- 38,000 movies (nothing current - mostly pre-1940's)
- 4,000,000 names (actors, directors, etc.)
- 25 genres
- 10 artist categories (actor, director, etc.)

I'll also post the Model classes that EF generated from the database. They should give you a head start.
